name: Continuous Integration (CI)
on: [push, pull_request]

env:
  ANGULAR_CLI_VERSION: 13 

jobs:
  build:
    name: Run security scans
    runs-on: ubuntu-latest

    # Run Security Scans
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
          node-version: 14
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    # Install node packages (npm ci)
    - name: "Install CLI tools"
      run: npm install -g @angular/cli@$ANGULAR_CLI_VERSION
    - name: "Install application minimalistically"
      run: |
          npm install --ignore-scripts
          cd frontend
          npm install --ignore-scripts --legacy-peer-deps
    
    # SAST tests
    - name: "OWASP Dependency Check"
      run: |
          chmod +x tools/dependency-check/bin/dependency-check.sh
          tools/dependency-check/bin/dependency-check.sh -s . -o output --disableAssembly

    - name: DevSkim
      uses: microsoft/devskim-action@v1
      with:
        directory-to-scan: /
        should-scan-archives: false
        output-filename: devskim-results.sarif
        output-directory: output

    # Publish the scan results as an artifact
    - uses: actions/upload-artifact@v2
      with: 
        name: scan-results
        path: output
